
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh my-test --zone=us-west4-b --command='/bin/sh /home/elitefxpro5505/pull.sh'